spring:
  profiles: default
  profiles.active: default
  application:
      name: XHipster
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
  mvc:
    locale: en_US
    date-format: dd/MM/yyyy HH:mm:ss
  http:
    multipart:
      enabled: true
      max-file-size: 3Mb
      max-request-size: 10Mb
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 1337
  tomcat:
    max-threads: 5
    uri-encoding: utf-8

security:
  basic:
    enabled: false


# Databases
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: "jdbc:mysql://localhost:6603/xhipster?jdbcCompliantTruncation=false&elideSetAutoCommits=true&useLocalSessionState=true&cachePrepStmts=true&cacheCallableStmts=true&alwaysSendSetIsolation=false&prepStmtCacheSize=4096&cacheServerConfiguration=true&prepStmtCacheSqlLimit=2048&zeroDateTimeBehavior=convertToNull&traceProtocol=false&useUnbufferedInput=false&useReadAheadInput=false&maintainTimeStats=false&useServerPrepStmts&cacheRSMetadata=true&verifyServerCertificate=false&useSSL=false&requireSSL=false"
  username: root
  password: password





logging:
  level:
    org.springframework.web: INFO
    springframework.security: DEBUG
    org.springframework.boot: INFO


daemon:
  appname: "XHipster"

endpoints:
  sensitive: false
  info:
    sensitive: false
  shutdown:
    enabled: false

management:
  security:
    enabled: true
  context-path: /admin/manage


